const RATE = 1;
const ORIGIN = { lat: -20.0109557, lon: -44.0094064 };
const TIMEOUT = 12000;
type C = { lat: number; lon: number };
type A = { street?: string; number?: string; neighborhood?: string; city?: string; state?: string; cep?: string };
type R = { lat?: string; lon?: string; display_name?: string; address?: { road?: string; pedestrian?: string; house_number?: string; suburb?: string; neighbourhood?: string; city?: string; town?: string; municipality?: string; state?: string; postcode?: string } };
const norm = (v?: string) => (v ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();
const dig = (v?: string) => (v ?? '').replace(/\D/g, '');
const fetchT = async (u: string | URL, init: RequestInit = {}) => { const c = new AbortController(); const t = setTimeout(() => c.abort(), TIMEOUT); try { return await fetch(u, { ...init, signal: c.signal, cache: 'no-store' }); } finally { clearTimeout(t); } };
const coords = (a: unknown, b: unknown): C | null => { const lat = Number(a), lon = Number(b); return Number.isFinite(lat) && Number.isFinite(lon) && lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180 ? { lat, lon } : null; };
const stateOK = (a: string, b: string) => { if (!b || a === b || a.includes(b) || b.includes(a)) return true; const m: Record<string,string> = { mg:'minas gerais', sp:'sao paulo', rj:'rio de janeiro', es:'espirito santo', pr:'parana', sc:'santa catarina', rs:'rio grande do sul', ba:'bahia', go:'goias', df:'distrito federal' }; return m[a] === b || m[b] === a; };
async function nom(q: string): Promise<R[]> { try { const u = new URL('https://nominatim.openstreetmap.org/search'); u.searchParams.set('format','jsonv2'); u.searchParams.set('addressdetails','1'); u.searchParams.set('countrycodes','br'); u.searchParams.set('limit','10'); u.searchParams.set('q',q); const r = await fetchT(u,{headers:{Accept:'application/json','Accept-Language':'pt-BR','User-Agent':'DoceriaFrete/4.0'}}); return r.ok ? await r.json() : []; } catch { return []; } }
const queries = (a: A) => { const s=a.street?.trim(), n=a.number?.trim(), b=a.neighborhood?.trim(), c=a.city?.trim() || 'Belo Horizonte', e=a.state?.trim() || 'MG', p=dig(a.cep); return [...new Set([[s,n,b,c,e,'Brasil'],[s,n,c,e,'Brasil'],[s,n,b,c,'Brasil'],[s,n,p,c,e,'Brasil'],[s,b,c,e,'Brasil'],[s,c,e,'Brasil'],[s,p,c,e,'Brasil']].map(x=>x.filter(Boolean).join(', ')).filter(Boolean))]; };
async function find(a: A): Promise<C | null> { const street=norm(a.street), number=dig(a.number), city=norm(a.city || 'Belo Horizonte'), state=norm(a.state || 'Minas Gerais'), neighborhood=norm(a.neighborhood), list: { c:C; score:number }[]=[]; for (const q of queries(a)) for (const r of await nom(q)) { const x=coords(r.lat,r.lon); if(!x) continue; const z=r.address || {}; const rs=norm(z.road || z.pedestrian || r.display_name), rc=norm(z.city || z.town || z.municipality), rst=norm(z.state), rn=dig(z.house_number), rb=norm(z.suburb || z.neighbourhood); const tokens=street.split(' ').filter(t=>t.length>2); if(!tokens.length || !tokens.every(t=>rs.includes(t))) continue; if(rc && !rc.includes(city) && !city.includes(rc)) continue; if(!stateOK(state,rst)) continue; if(number && rn && number!==rn) continue; let score=30; if(number && rn===number) score+=100; if(!rn) score-=20; if(neighborhood && rb && (rb.includes(neighborhood)||neighborhood.includes(rb))) score+=20; if(a.cep && dig(z.postcode)===dig(a.cep)) score+=20; list.push({c:x,score}); } list.sort((a,b)=>b.score-a.score); return list[0]?.c || null; }
async function route(a:C,b:C): Promise<number|null> { const u=new URL(`https://router.project-osrm.org/route/v1/driving/${a.lon},${a.lat};${b.lon},${b.lat}`); u.searchParams.set('overview','false'); for(let i=0;i<2;i++){try{const r=await fetchT(u,{headers:{Accept:'application/json'}}); if(r.ok){const j=await r.json(); const d=j.routes?.[0]?.distance; if(j.code==='Ok'&&Number.isFinite(d)) return d;} }catch{} if(i===0) await new Promise(r=>setTimeout(r,700));} return null; }
export async function POST(req: Request) { try { const a=(await req.json()) as A; if(!a.street?.trim()||!a.number?.trim()||!a.city?.trim()||!a.state?.trim()) return Response.json({error:'Endereço incompleto. Informe rua, número, cidade e estado.'},{status:400}); const d=await find(a); if(!d) return Response.json({error:'Não foi possível localizar este endereço com segurança. Confira os dados informados.'},{status:422}); const meters=await route(ORIGIN,d); if(meters===null) return Response.json({error:'Não foi possível calcular a rota agora. Tente novamente.'},{status:503}); const one=meters/1000, round=one*2; return Response.json({fee:Number(round.toFixed(2)),oneWayKm:Number(one.toFixed(2)),roundTripKm:Number(round.toFixed(2))},{headers:{'Cache-Control':'no-store'}}); } catch { return Response.json({error:'Erro ao calcular a entrega. Tente novamente.'},{status:500}); } }
